# Generated by Django 5.1.1 on 2024-12-15 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=10)),
                ('precio', models.FloatField()),
                ('marca', models.CharField(max_length=20)),
                ('codigo_interno', models.CharField(max_length=10)),
                ('presentacion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('imagen_producto', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('disponibilidad', models.BooleanField(default=True)),
                ('stock', models.IntegerField()),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
